# Site settings
title: Griswald Brooks
email: griswald.brooks@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Roboticist and maker.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://griswaldbrooks.com" # the base hostname & protocol for your site
github_username: griswaldbrooks
linkedin_username: griswaldbrooks

# Build settings
markdown: kramdown

include: ["_pages", "_images", "downloads"]

collections:
 projects: # The collection where I keep all my robot projects.
  output: true

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: page
      permalink: /:collection/:path/
      categories: projects
