# Site settings
title: Griswald Brooks
email: griswald.brooks@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Roboticist and maker.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://griswaldbrooks.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  griswaldbrooks

# Build settings
markdown: kramdown
